### PR TITLE
fix(#94): show all days when filtered by last 7 or last 30

### LINKED ISSUE #94: Gráfico energía diaria
La escala del eje de abscisas es arbitraria. 

En esta imagen a primera vista parece que hay cargas casi todos los días desde el 24/12/25, con la excepción del 19/1/26.

Sin embargo no cargué el 29/12, ni el 2/1 ni tampoco entre el 4/1 al 9/1, ni del 11 al 17 de enero. 

Esos días "en blanco" simplemente no aparecen. Pero en cambio si aparece el 19/1 y el 23/12 ¿?

### PR DESCRIPTION
**Pull request by MARMdeveloper**
## Summary
Display all days in summary charts for charges when the filter is set to 7 or 30 days.

We also apply the same behavior to drives charts.

## Changes
Creation list of days to be graphed, regardless of whether there is data or not.

Closes #94

### CODE REVIEW

File: app/src/main/java/com/matedroid/ui/screens/drives/DrivesViewModel.kt [hunk 1]
```diff
@@ -274,50 +271,77 @@ class DrivesViewModel @Inject constructor(
...
-    private fun calculateChartData(drives: List<DriveData>, granularity: DriveChartGranularity): List<DriveChartData> {
+    private fun calculateChartData(drives: List<DriveData>, granularity: DriveChartGranularity, startDate: LocalDate?): List<DriveChartData> {
         if (drives.isEmpty()) return emptyList()
 
         val formatter = DateTimeFormatter.ISO_DATE_TIME
         val weekFields = WeekFields.of(Locale.getDefault())
 
-        return drives
-            .mapNotNull { drive ->
+        //  Group the charges by day
```
Comment (vide) [inline app/src/main/java/com/matedroid/ui/screens/drives/DrivesViewModel.kt]:
```suggestion
        //  Group the drives by day
```
